MAX_STEM_LENGTH_AVG = 10
MAX_STEM_THICKNESS_AVG = 5
MAX_GROWTH_PATTERN_CLUMP_AVG_COUNT = 20
MAX_GROWTH_PATTERN_CLUSTER_AVG_COUNT = 50
MAX_GROWTH_PATTERN_CLUSTER_AVG_DISTANCE = 10
GILLS_FANS_DENSITY_MIN = 0.8
GILLS_FANS_TOP_LEVEL_COUNT_MAX = 100
GILLS_HONEYCOMB_DENSITY_MIN = 0.1
