STEM_LENGTH_AVG_MAX = 10
STEM_LENGTH_MAX = 10
STEM_THICKNESS_AVG_MAX = 5
STEM_THICKNESS_MAX = 5

GROWTH_PATTERN_CLUMP_COUNT_AVG_MAX = 20
GROWTH_PATTERN_CLUMP_COUNT_MAX = 100
GROWTH_PATTERN_CLUSTER_COUNT_AVG_MAX = 50
GROWTH_PATTERN_CLUSTER_COUNT_MAX = 50
GROWTH_PATTERN_CLUSTER_DISTANCE_AVG_MAX = 10

GILLS_FANS_DENSITY_MIN = 0.8
GILLS_FANS_TOP_LEVEL_COUNT_MAX = 100
GILLS_HONEYCOMB_DENSITY_MIN = 0.1
